USE db_incidencias;


-- ------- CREATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_ROL_CREATE;
DELIMITER //
CREATE PROCEDURE USP_TB_ROL_CREATE (OUT id INT, descrip VARCHAR(50))
BEGIN
	INSERT INTO `db_incidencias`.`tb_rol`
				(`descrip_rol`)
	VALUES
				(descrip);


	SELECT LAST_INSERT_ID() INTO id;
END //
DELIMITER ;



-- ------- READ PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ROL_READ;
DELIMITER //
CREATE PROCEDURE USP_TB_ROL_READ ()
BEGIN
	SELECT * FROM TB_ROL;
END //
DELIMITER ;


-- ------- UPDATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_ROL_UPDATE;
DELIMITER //
CREATE PROCEDURE USP_TB_ROL_UPDATE(id INT, descrip VARCHAR(50))
BEGIN
	UPDATE `db_incidencias`.`tb_rol`
	SET
			`descrip_rol` = descrip
	WHERE `id_rol` = id;

END
// DELIMITER ;


-- ------- DELETE PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ROL_DELETE;
DELIMITER //
CREATE PROCEDURE USP_TB_ROL_DELETE(id INT)
BEGIN
	DELETE FROM TB_ROL WHERE id_rol = id;
END
// DELIMITER ;


-- -------- OBTAIN PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ROL_OBTAIN;
DELIMITER //
CREATE PROCEDURE USP_TB_ROL_OBTAIN (id INT)
BEGIN
	SELECT * FROM TB_ROL
    WHERE id_rol = id;
END //
DELIMITER ;