USE db_incidencias;


-- ------- CREATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_CREATE;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_CREATE (OUT id INT, raz_soc VARCHAR(50))
BEGIN
	INSERT INTO `db_incidencias`.`tb_empresa`
				(`raz_soc_empresa`)
	VALUES
				(ras_soc);

	SELECT LAST_INSERT_ID() INTO id;
END //
DELIMITER ;



-- ------- READ PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_READ;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_READ ()
BEGIN
	SELECT * FROM TB_EMPRESA;
END //
DELIMITER ;


-- ------- UPDATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_UPDATE;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_UPDATE(id INT, raz_soc VARCHAR(50))
BEGIN
	UPDATE `db_incidencias`.`tb_empresa`
	SET
			`raz_soc_empresa` = raz_soc
	WHERE `id_empresa` = id;

END
// DELIMITER ;


-- ------- DELETE PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_DELETE;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_DELETE(id INT)
BEGIN
	DELETE FROM TB_EMPRESA WHERE id_empresa = id;
END
// DELIMITER ;


-- -------- OBTAIN PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_OBTAIN;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_OBTAIN (id INT)
BEGIN
	SELECT * FROM TB_EMPRESA
    WHERE id_empresa = id;
END //
DELIMITER ;