USE db_incidencias;


-- ------- CREATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_CLIENTE_CREATE;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_CLIENTE_CREATE (idEmpresa INT, idCliente INT)
BEGIN
	INSERT INTO `db_incidencias`.`tb_empresa_cliente`
				(`id_empresa`,
				`id_cliente`)
	VALUES
				(idEmpresa,
				idCliente);

END //
DELIMITER ;



-- ------- READ PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_CLIENTE_READ;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_CLIENTE_READ ()
BEGIN
	SELECT * FROM TB_EMPRESA_CLIENTE;
END //
DELIMITER ;


-- ------- DELETE PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_CLIENTE_DELETE;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_CLIENTE_DELETE(idEmpresa INT, idCliente INT)
BEGIN
	DELETE FROM TB_EMPRESA_CLIENTE WHERE id_empresa = idEmpresa AND id_cliente = idCliente;
END
// DELIMITER ;


-- -------- OBTAIN PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_EMPRESA_CLIENTE_OBTAIN;
DELIMITER //
CREATE PROCEDURE USP_TB_EMPRESA_CLIENTE_OBTAIN (id INT)
BEGIN
	SELECT * FROM TB_EMPRESA_CLIENTE
    WHERE id_empresa = idEmpresa AND id_cliente = idCliente;
END //
DELIMITER ;