USE db_incidencias;


-- ------- CREATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_PRIORIDAD_CREATE;
DELIMITER //
CREATE PROCEDURE USP_TB_PRIORIDAD_CREATE (OUT id INT, descrip VARCHAR(50))
BEGIN
	INSERT INTO `db_incidencias`.`tb_prioridad`
				(`descrip_prioridad`)
	VALUES
				(descrip);

	SELECT LAST_INSERT_ID() INTO id;
END //
DELIMITER ;



-- ------- READ PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_PRIORIDAD_READ;
DELIMITER //
CREATE PROCEDURE USP_TB_PRIORIDAD_READ ()
BEGIN
	SELECT * FROM TB_PRIORIDAD;
END //
DELIMITER ;


-- ------- UPDATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_PRIORIDAD_UPDATE;
DELIMITER //
CREATE PROCEDURE USP_TB_PRIORIDAD_UPDATE(id INT, descrip VARCHAR(50))
BEGIN
	UPDATE `db_incidencias`.`tb_prioridad`
	SET
			`descrip_prioridad` = descrip
	WHERE `id_prioridad` = id;

END
// DELIMITER ;


-- ------- DELETE PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_PRIORIDAD_DELETE;
DELIMITER //
CREATE PROCEDURE USP_TB_PRIORIDAD_DELETE(id INT)
BEGIN
	DELETE FROM TB_PRIORIDAD WHERE id_prioridad = id;
END
// DELIMITER ;


-- -------- OBTAIN PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_PRIORIDAD_OBTAIN;
DELIMITER //
CREATE PROCEDURE USP_TB_PRIORIDAD_OBTAIN (id INT)
BEGIN
	SELECT * FROM TB_PRIORIDAD
    WHERE id_prioridad = id;
END //
DELIMITER ;