USE db_incidencias;


-- ------- CREATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_ESTADO_CREATE;
DELIMITER //
CREATE PROCEDURE USP_TB_ESTADO_CREATE (OUT id INT, descrip VARCHAR(50))
BEGIN
	INSERT INTO `db_incidencias`.`tb_estado`
				(`descrip_estado`)
	VALUES
				(descrip);

	SELECT LAST_INSERT_ID() INTO id;
END //
DELIMITER ;



-- ------- READ PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ESTADO_READ;
DELIMITER //
CREATE PROCEDURE USP_TB_ESTADO_READ ()
BEGIN
	SELECT * FROM TB_ESTADO;
END //
DELIMITER ;


-- ------- UPDATE PROCEDURE ----------
DROP PROCEDURE IF EXISTS USP_TB_ESTADO_UPDATE;
DELIMITER //
CREATE PROCEDURE USP_TB_ESTADO_UPDATE(id INT, descrip VARCHAR(50))
BEGIN
	UPDATE `db_incidencias`.`tb_estado`
	SET
			`descrip_estado` = descrip
	WHERE `id_estado` = id;
END
// DELIMITER ;


-- ------- DELETE PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ESTADO_DELETE;
DELIMITER //
CREATE PROCEDURE USP_TB_ESTADO_DELETE(id INT)
BEGIN
	DELETE FROM TB_ESTADO WHERE id_estado = id;
END
// DELIMITER ;


-- -------- OBTAIN PROCEDURE -----------
DROP PROCEDURE IF EXISTS USP_TB_ESTADO_OBTAIN;
DELIMITER //
CREATE PROCEDURE USP_TB_ESTADO_OBTAIN (id INT)
BEGIN
	SELECT * FROM TB_ESTADO
    WHERE id_estado = id;
END //
DELIMITER ;